// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bexo/AddUpdate.tsx": () => import("../components/mockups/bexo/AddUpdate.tsx"),
  "./components/mockups/bexo/CardFlow.tsx": () => import("../components/mockups/bexo/CardFlow.tsx"),
  "./components/mockups/bexo/Dashboard.tsx": () => import("../components/mockups/bexo/Dashboard.tsx"),
  "./components/mockups/bexo/Generating.tsx": () => import("../components/mockups/bexo/Generating.tsx"),
  "./components/mockups/bexo/HandleSetup.tsx": () => import("../components/mockups/bexo/HandleSetup.tsx"),
  "./components/mockups/bexo/Login.tsx": () => import("../components/mockups/bexo/Login.tsx"),
  "./components/mockups/bexo/PortfolioLive.tsx": () => import("../components/mockups/bexo/PortfolioLive.tsx"),
  "./components/mockups/bexo/ProfilePhoto.tsx": () => import("../components/mockups/bexo/ProfilePhoto.tsx"),
  "./components/mockups/bexo/ResumeUpload.tsx": () => import("../components/mockups/bexo/ResumeUpload.tsx"),
  "./components/mockups/bexo/Splash.tsx": () => import("../components/mockups/bexo/Splash.tsx")
};
